# Cargomail
domain_name: ${DOMAIN_NAME}

# Database
db_path: ${DB_PATH}

# File Storage
storage_path: ${STORAGE_PATH}

# App
app_api_bind: ${APP_API_BIND}

# GRIP
grip_api_bind: ${GRIP_API_BIND}
grip_cert_file: ${GRIP_CERT_FILE}
grip_key_file: ${GRIP_KEY_FILE}