domain_name: ${DOMAIN_NAME}
storage_path: ${STORAGE_PATH}
database_path: ${DATABASE_PATH}
resources_path: ${RESOURCES_PATH}
transfer_cert_path: ${TRANSFER_CERT_PATH}
transfer_key_path: ${TRANSFER_KEY_PATH}
provider_bind: ${PROVIDER_BIND}
transfer_bind: ${TRANSFER_BIND}

